version: '3.7'

services:
  chihaya:
    image: {{ chihaya_image }}
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "10"
    networks:
      - terragraph_net
    volumes:
      - "{{ chihaya_path }}/chihaya.yml:/etc/chihaya.yml"
    command: ["--config", "/etc/chihaya.yml"]

networks:
  terragraph_net:
    external: true
